// apps/admin/src/pages/Login/index.tsx
import { Buffer } from "buffer";
import { Form, Input, Button, message } from "antd";
import { FC, useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { useNavigate } from "react-router-dom";
import { adminUserDoLogin, AdminUserLoginParams } from "@/apis/admin";
import { getCaptcha } from "@/apis/common";
import LogoSvg from "@/assets/svg/logo.svg";

export const LoginPage: FC = () => {
  const navigate = useNavigate();

  const { t } = useTranslation();
  const [loading, setLoading] = useState(false);

  const [captcha, setCaptcha] = useState("");

  const onFinish = async (values: AdminUserLoginParams) => {
    if (!captcha) {
      return;
    }

    try {
      setLoading(true);
      const res = await adminUserDoLogin(values);

      if (res.code === 200) {
        localStorage.setItem("token", res.data.token);
        navigate("/admin/home");
      }
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } catch (error: any) {
      message.error(error.message);
    } finally {
      setLoading(false);
    }
  };

  const fetchCaptcha = async () => {
    try {
      const res = await getCaptcha();

      setCaptcha(res.data);
    } catch (error) {
      /* empty */
    }
  };

  useEffect(() => {
    if (!captcha) {
      fetchCaptcha();
    }
  }, []);

  return (
    <div className="full flex-center bg-gradientPink">
      <div className="bg-white rounded-md px-12 w-card h-card">
        <div className="text-38px h-150 font-semibold text-center flex-center">{t("login")}</div>

        <img w="100px" src={LogoSvg} alt="" />

        <Form name="normal_login" className="login-form" initialValues={{ remember: true }} onFinish={onFinish}>
          <Form.Item name="username" rules={[{ required: true, message: `${t("please input your Username")}` }]}>
            <Input className="!border-0 !border-b !border-b-grey" size="large" placeholder={`${t("username")}`} />
          </Form.Item>
          <Form.Item name="password" rules={[{ required: true, message: `${t("please input your Password")}` }]}>
            <Input
              className="!border-0 !border-b !border-b-grey"
              size="large"
              type="password"
              placeholder={`${t("password")}`}
              autoComplete="off"
            />
          </Form.Item>
          <Form.Item>
            <div className="w-full flex">
              <Form.Item noStyle name="code" rules={[{ required: true, message: `${t("please input your captcha")}` }]}>
                <Input className="rounded-br-none rounded-tr-none" placeholder={`${t("captcha")}`} size="large" />
              </Form.Item>
              <img
                src={captcha ? `data:image/svg+xml;base64,${Buffer.from(captcha).toString("base64")}` : ""}
                alt={`${t("loading")}`}
                onClick={fetchCaptcha}
                className="rounded-br-sm rounded-tr-sm"
              />
            </div>
          </Form.Item>

          <Form.Item>
            <Button className="w-full !bg-gradientViolet !text-white" size="large" htmlType="submit" loading={loading}>
              {t("config")}
            </Button>
            <div className="mt-sm flex justify-between">
              <div>
                {t("Don't have account")}
                <a href="#">{t("signUp")}</a>
              </div>
              <a className="login-form-forgot" href="">
                {t("forgotPassword")}
              </a>
            </div>
          </Form.Item>
        </Form>
      </div>
    </div>
  );
};

// apps/frontend/src/views/Login/index.vue
<script setup lang="ts">
import { Buffer } from "buffer";
import { message } from "ant-design-vue";
import { reactive, ref, onMounted } from "vue";
import { useRouter } from "vue-router";
import { getCaptcha } from "@/apis/common";
import { userDoLogin } from "@/apis/user";
import LogoSvg from "@/assets/svg/logo.svg";

interface FormState {
  username: string;
  password: string;
  code: string;
}

const formState = reactive<FormState>({
  username: "",
  password: "",
  code: "",
});

const captcha = ref("");

const loading = ref(false);
const router = useRouter();

const fetchCaptcha = async () => {
  try {
    const res = await getCaptcha();

    if (res.code === 200) {
      captcha.value = `data:image/svg+xml;base64,${Buffer.from(res.data).toString("base64")}`;
    }
  } catch (error) {
    // throw error;
  }
};

onMounted(() => {
  fetchCaptcha();
});

const onFinish = async (values: FormState) => {
  try {
    loading.value = true;

    const res = await userDoLogin(values);

    if (res.code === 200) {
      localStorage.setItem("token", res.data.token);
      router.push("/home");
    }
  } catch (error: any) {
    message.error(error.message);
  } finally {
    loading.value = false;
  }
};
</script>

<template>
  <div class="full flex-center bg-gradientPink">
    <div class="bg-white rounded-md px-12 w-card h-card relative">
      <div class="text-38px h-140 font-semibold text-center flex-center">Login</div>

      <img class="absolute top-12px right-24px" w="100px" :src="LogoSvg" alt="加载中" />

      <a-form :model="formState" name="login_form" @finish="onFinish">
        <a-form-item name="username" :rules="[{ required: true, message: 'Please input your username!' }]">
          <a-input v-model:value="formState.username" class="input" size="large" placeholder="用户名">
            <template #prefix>
              <UserOutlined class="site-form-item-icon" />
            </template>
          </a-input>
        </a-form-item>

        <a-form-item name="password" :rules="[{ required: true, message: 'Please input your password!' }]">
          <a-input-password
            v-model:value="formState.password"
            autocomplete="off"
            class="input"
            size="large"
            placeholder="密码"
          >
            <template #prefix>
              <LockOutlined class="site-form-item-icon" />
            </template>
          </a-input-password>
        </a-form-item>

        <a-form-item name="code" :rules="[{ required: true, message: 'Please input your code!' }]">
          <div class="w-full flex">
            <a-input v-model:value="formState.code" class="input" size="large" placeholder="验证码" />

            <img alt="loading" :src="captcha" :onClick="fetchCaptcha" />
          </div>
        </a-form-item>

        <a-form-item>
          <a-button class="!mt-12px w-full !bg-gradientViolet !text-white !rounded-smm" size="large" html-type="submit">
            登录
          </a-button>
          <div class="mt-sm flex justify-between">
            <div>
              Don't have account
              <a href="#">sign up</a>
            </div>
            <a class="login-form-forgot" href="">forgot password</a>
          </div>
        </a-form-item>
      </a-form>
    </div>
  </div>
</template>

<style scoped>
.input {
  --at-apply: "!border-0 !border-b !border-b-grey hover:!border-b-purple hover:!border-r-none";
}
</style>
